### ISSUE TITLE
截图后显示出来图片变模糊了？

### ISSUE THREAD

**Issue by wzhsh90** [AlloyTeam/AlloyCrop#27]
文字还出现毛边

**Comment by dntzhang** [comment]
output设置一下

**Comment by wzhsh90** [comment]
output 用的默认：1

**Comment by wzhsh90** [comment]
![image](https://user-images.githubusercontent.com/16187191/43355857-16d24914-9297-11e8-906e-299242130ef0.png)
栽剪的大小：width 与height 都比原图小

**Comment by dntzhang** [comment]
output设置成2

**Comment by wzhsh90** [comment]
那我width 与 height 设置的时候是不是要先设置为上面的一半？

**Comment by wzhsh90** [comment]
还是有问题，一样的效果

**Comment by wzhsh90** [comment]
另外还不能与这个hidpi-canvas 结合使用，一结合就有问题了

**Comment by dntzhang** [comment]
为什么

**Comment by wzhsh90** [comment]
这个得请教您了

**Comment by dntzhang** [comment]
我写的demo output设置成2就不会。还有同事写的demo线上运行了几年了都不会。

**Comment by dntzhang** [comment]
为什么你得会模糊。output设置成4？

**Comment by dntzhang** [comment]
不过设置成4有点伤心病狂，一般设置成2。要么canvas宽高设置成2倍。很简单的问题哈

**Comment by dntzhang** [comment]
再不行设置成8，canvas宽高设置成4倍

**Comment by wzhsh90** [comment]
output:2 时，用户看到的是一个小窗口，但栽出来的图片确不是自己想要的

**Comment by dntzhang** [comment]
官方demo有问题吗？拿官方demo改下？

**Comment by dntzhang** [comment]
或者debug下源码？

**Comment by dntzhang** [comment]
原理在 readme 里。

**Comment by Smile-dan** [comment]
找到解决的办法了吗？我的也模糊，和output没关系，设置成2也模糊

**Comment by eachmawzw** [comment]
出现的同样的问题，原因是retina屏幕需要展示的图片宽高应该为展示区域乘以设备的物理像素分辨率与CSS像素分辨率的比值（DPR）。类AlloyCrop的方法output确实可以自定义画布（canvas）的宽高，但是好像代码中画板的宽高通过计算后，并没有乘以DPR，所以在使用output:2时，会发现裁剪后的图片在画布的左上角画了一个一半大小的图片。我没有仔细看代码，仅仅修改了关键部分，这个问题得到了解决。
```
crop: function () {
    this.calculateRect();
    this.ctx.drawImage(this.img, this.crop_rect[0], this.crop_rect[1], this.crop_rect[2], this.crop_rect[3], 0, 0, this.crop_rect[2]*this.img.scaleX*this.output, this.crop_rect[3]*this.img.scaleY*this.output);
},
```
我会试着提一下PR。

**Comment by dntzhang** [comment]
已被 @eachmawzw 修复~~
