### ISSUE TITLE
关于canvas的宽高设置

### ISSUE THREAD

**Issue by jesse-li** [AlloyTeam/AlloyCrop#6]
源码中有这样一段
this.cover.width = window.innerWidth;
this.cover.height = window.innerHeight;
一般情况下没有问题，但是在ios9、iphone6及以上有个bug，会导致获取的宽高不正确。
虽然这个bug，可以通过在‘viewport’中添加‘shrink-to-fit=no’来避免，但是免不了一顿查找bug的过程。。。
可以考虑换成document.documentElement.clientXXXX

**Comment by dntzhang** [comment]
赞，收到。 我看下~~
